BROKER_URL = 'amqp://localhost//'
CELERY_RESULT_BACKEND = 'rpc'

CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_SERIALIZER = 'pickle'
CELERY_ACCEPT_CONTENT=['pickle']
CELERY_TIMEZONE = 'Europe/London'
CELERY_ENABLE_UTC = True


#CELERYD_CONCURRENCY = 4
